src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private string $email;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private string $password;

    #[ORM\Column(type: 'boolean')]
    private bool $isVerified = false;

    #[ORM\Column]
    private int $birthYear;

    #[ORM\Column(length: 255)]
    private string $country;

    #[ORM\Column(length: 255)]
    private string $completedEducationLevel;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $completedEducationUniversityName = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $completedEducationFacultyName = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $currentEducationLevel = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $studyProgram = null;

    #[ORM\Column(nullable: true)]
    private ?int $academicYear = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $universityName = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $facultyName = null;

    #[ORM\Column(length: 255)]
    private ?string $fieldOfExperience = null;

    #[ORM\Column]
    private ?int $yearsOfExperience = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $courseList = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $favoriteMethod = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $currentJobTitle = null;

    #[ORM\Column]
    private ?bool $stayInTouch = null;

    #[ORM\Column]
    private ?bool $deleted = false;

    #[ORM\Column]
    private ?bool $evaluateGlobalCategories = true;

    #[ORM\ManyToMany(targetEntity: ExerciseTypeCategory::class)]
    private Collection $exerciseTypeCategories;

    public function __construct()
    {
        $this->exerciseTypeCategories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getBirthYear(): ?int
    {
        return $this->birthYear;
    }

    public function setBirthYear(int $birthYear): self
    {
        $this->birthYear = $birthYear;

        return $this;
    }

    public function getYearsOfExperience(): ?int
    {
        return $this->yearsOfExperience;
    }

    public function setYearsOfExperience(int $yearsOfExperience): self
    {
        $this->yearsOfExperience = $yearsOfExperience;

        return $this;
    }

    public function getCurrentEducationLevel(): ?string
    {
        return $this->currentEducationLevel;
    }

    public function setCurrentEducationLevel(?string $currentEducationLevel): self
    {
        $this->currentEducationLevel = $currentEducationLevel;

        return $this;
    }

    public function getAcademicYear(): ?int
    {
        return $this->academicYear;
    }

    public function setAcademicYear(?int $academicYear): self
    {
        $this->academicYear = $academicYear;

        return $this;
    }

    public function getUniversityName(): ?string
    {
        return $this->universityName;
    }

    public function setUniversityName(?string $universityName): self
    {
        $this->universityName = $universityName;

        return $this;
    }

    public function getFacultyName(): ?string
    {
        return $this->facultyName;
    }

    public function setFacultyName(?string $facultyName): self
    {
        $this->facultyName = $facultyName;

        return $this;
    }

    public function getStudyProgram(): ?string
    {
        return $this->studyProgram;
    }

    public function setStudyProgram(?string $studyProgram): self
    {
        $this->studyProgram = $studyProgram;

        return $this;
    }

    public function getFieldOfExperience(): ?string
    {
        return $this->fieldOfExperience;
    }

    public function setFieldOfExperience(string $fieldOfExperience): self
    {
        $this->fieldOfExperience = $fieldOfExperience;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getCourseList(): ?string
    {
        return $this->courseList;
    }

    public function setCourseList(?string $courseList): self
    {
        $this->courseList = $courseList;

        return $this;
    }

    public function getFavoriteMethod(): ?string
    {
        return $this->favoriteMethod;
    }

    public function setFavoriteMethod(?string $favoriteMethod): self
    {
        $this->favoriteMethod = $favoriteMethod;

        return $this;
    }

    public function isStayInTouch(): ?bool
    {
        return $this->stayInTouch;
    }

    public function setStayInTouch(bool $stayInTouch): self
    {
        $this->stayInTouch = $stayInTouch;

        return $this;
    }

    public function getCurrentJobTitle(): ?string
    {
        return $this->currentJobTitle;
    }

    public function setCurrentJobTitle(?string $currentJobTitle): self
    {
        $this->currentJobTitle = $currentJobTitle;

        return $this;
    }

    public function isDeleted(): ?bool
    {
        return $this->deleted;
    }

    public function setDeleted(bool $deleted): self
    {
        $this->deleted = $deleted;

        return $this;
    }

    /**
     * @return string
     */
    public function getCompletedEducationLevel(): string
    {
        return $this->completedEducationLevel;
    }

    /**
     * @param string $completedEducationLevel
     */
    public function setCompletedEducationLevel(string $completedEducationLevel): void
    {
        $this->completedEducationLevel = $completedEducationLevel;
    }

    /**
     * @return string|null
     */
    public function getCompletedEducationUniversityName(): ?string
    {
        return $this->completedEducationUniversityName;
    }

    /**
     * @param string|null $completedEducationUniversityName
     */
    public function setCompletedEducationUniversityName(?string $completedEducationUniversityName): void
    {
        $this->completedEducationUniversityName = $completedEducationUniversityName;
    }

    /**
     * @return string|null
     */
    public function getCompletedEducationFacultyName(): ?string
    {
        return $this->completedEducationFacultyName;
    }

    /**
     * @param string|null $completedEducationFacultyName
     */
    public function setCompletedEducationFacultyName(?string $completedEducationFacultyName): void
    {
        $this->completedEducationFacultyName = $completedEducationFacultyName;
    }

    public function isEvaluateGlobalCategories(): ?bool
    {
        return $this->evaluateGlobalCategories;
    }

    public function setEvaluateGlobalCategories(bool $evaluateGlobalCategories): self
    {
        $this->evaluateGlobalCategories = $evaluateGlobalCategories;

        return $this;
    }

    /**
     * @return Collection<int, ExerciseTypeCategory>
     */
    public function getExerciseTypeCategories(): Collection
    {
        return $this->exerciseTypeCategories;
    }

    public function addExerciseTypeCategory(ExerciseTypeCategory $exerciseTypeCategory): self
    {
        if (!$this->exerciseTypeCategories->contains($exerciseTypeCategory)) {
            $this->exerciseTypeCategories->add($exerciseTypeCategory);
        }

        return $this;
    }

    public function removeExerciseTypeCategory(ExerciseTypeCategory $exerciseTypeCategory): self
    {
        $this->exerciseTypeCategories->removeElement($exerciseTypeCategory);

        return $this;
    }



}

templates/user/item.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Users'|trans }}{% endblock %}

{% block body %}
    <h1 class="mt-3 h2">{{ 'Edit user'|trans }} #{{ user.id }}</h1>
    {{ form(form) }}
{% endblock %}

templates/user/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Users'|trans }}{% endblock %}

{% block body %}
    <h1 class="mt-3 h2">{{ 'Users'|trans }}</h1>
    {{ form_start(filter_form) }}
    <div class="row">
        <div class="col-3">
            {{ form_row(filter_form.email) }}
        </div>
        <div class="col-3">
            {{ form_row(filter_form.verified) }}
        </div>
        <div class="col-3">
            {{ form_row(filter_form.category) }}
        </div>
        <div class="col-3 pt-4 text-end">
            {{ form_widget(filter_form.submit) }}
        </div>
    </div>
    {{ form_end(filter_form) }}
    <table class="table">
        <thead>
        <tr>
            <th>{% if app.request.get('order_by') == 'id' %}
                    {% if app.request.get('order_direction') == 'asc' %}
                        <a href="{{ path(app.request.attributes.get('_route'), app.request.get('_route_params')|merge({'order_by': 'id', 'order_direction': 'desc'})) }}"># <i class="bi bi-chevron-up"></i></a>
                    {% else %}
                        <a href="{{ path(app.request.attributes.get('_route'), app.request.get('_route_params')|merge({'order_by': 'none', 'order_direction': 'none'})) }}"># <i class="bi bi-chevron-down"></i></a>
                    {% endif %}
                {% else %}
                    <a href="{{ path(app.request.attributes.get('_route'), app.request.get('_route_params')|merge({'order_by': 'id', 'order_direction': 'asc'})) }}">#</a>
                {% endif %}
            </th>
            <th>{% if app.request.get('order_by') == 'email' %}
                    {% if app.request.get('order_direction') == 'asc' %}
                        <a href="{{ path(app.request.attributes.get('_route'), app.request.get('_route_params')|merge({'order_by': 'email', 'order_direction': 'desc'})) }}">{{ 'Email'|trans }} <i class="bi bi-chevron-up"></i></a>
                    {% else %}
                        <a href="{{ path(app.request.attributes.get('_route'), app.request.get('_route_params')|merge({'order_by': 'none', 'order_direction': 'none'})) }}">{{ 'Email'|trans }} <i class="bi bi-chevron-down"></i></a>
                    {% endif %}
                {% else %}
                    <a href="{{ path(app.request.attributes.get('_route'), app.request.get('_route_params')|merge({'order_by': 'email', 'order_direction': 'asc'})) }}">{{ 'Email'|trans }}</a>
                {% endif %}
            </th>
            <th>{{ 'Is verified'|trans }}</th>
            <th>{{ 'Is universal evaluator'|trans }}</th>
            <th>{{ 'Is student'|trans }}</th>
            <th>{{ 'Country'|trans }}</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
        <tr>
            <td>{{ user.id }}</td>
            <td>{{ user.email }}</td>
            <td>{% if user.verified %}<i class="bi bi-check text-success"></i>{% else %}<i class="bi bi-x text-danger"></i>{% endif %}</td>
            <td>{% if user.evaluateGlobalCategories %}<i class="bi bi-check text-success"></i>{% else %}<i class="bi bi-x text-danger"></i>{% endif %}</td>
            <td>{% if user.currentEducationLevel %}<i class="bi bi-check text-success"></i>{% else %}<i class="bi bi-x text-danger"></i>{% endif %}</td>
            <td>{{ user.country|trans }}</td>
            <td>
                {% if not user.verified %}<a href="{{ path('app_users_verify', {id: user.id}) }}" class="btn btn-success btn-sm" title="{{ 'Verify'|trans }}" data-tooltip><i class="bi bi-check-circle"></i></a>{% endif %}
                <a href="{{ path('app_users_edit', {id: user.id}) }}" class="btn btn-primary btn-sm" title="{{ 'Edit'|trans }}" data-tooltip><i class="bi bi-pencil"></i></a>
                <a href="#" class="btn btn-danger btn-sm" data-tooltip data-toggle="modal" data-target="#promptModal" data-link="{{ path('app_users_delete', {id: user.id}) }}" title="{{ 'Delete'|trans }}"><i class="bi bi-trash"></i></a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="">
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                {% if page != 1 %}
                    <li class="page-item"><a class="page-link" href="{{ path(app.request.attributes.get('_route'), app.request.get('_route_params')|merge({'page': 1})) }}">{{ 'First'|trans }}</a></li>
                    <li class="page-item"><a class="page-link" href="{{ path(app.request.attributes.get('_route'), app.request.get('_route_params')|merge({'page': page - 1})) }}">{{ 'Previous'|trans }}</a></li>
                {% endif %}
                {% for p in 1..max_page  %}
                    {% if p == page %}
                        <li class="page-item active" aria-current="page"><a class="page-link" href="{{ path(app.request.attributes.get('_route'), app.request.get('_route_params')|merge({'page': p})) }}">{{ p }}</a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="{{ path(app.request.attributes.get('_route'), app.request.get('_route_params')|merge({'page': p})) }}">{{ p }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page != max_page %}
                    <li class="page-item"><a class="page-link" href="{{ path(app.request.attributes.get('_route'), app.request.get('_route_params')|merge({'page': page + 1})) }}">{{ 'Next'|trans }}</a></li>
                    <li class="page-item"><a class="page-link" href="{{ path(app.request.attributes.get('_route'), app.request.get('_route_params')|merge({'page': max_page})) }}">{{ 'Last'|trans }}</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="promptModal" tabindex="-1" aria-labelledby="promptModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="promptModalLabel">{{ 'Delete confirmation'|trans }}</h1>
                    <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {{ 'Do you really want to delete this item?'|trans }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ 'Close'|trans }}</button>
                    <a href="#" class="btn btn-primary delete-btn">{{ 'Yes, delete!'|trans }}</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js" integrity="sha512-2rNj2KJ+D8s1ceNasTIex6z4HWyOnEYLVC3FigGOmyQCZc2eBXKgOxQmo3oKLHyfcj53uz4QMsRCWNbLd32Q1g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    {{ parent() }}

    <script>

        const tooltipTriggerList = document.querySelectorAll('[data-tooltip]')
        const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))

        $('#promptModal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget);
            var link = button.data('link');
            var modal = $(this);
            modal.find('.modal-footer .delete-btn').attr('href', link);
        });

    </script>

{% endblock %}